### ISSUE TITLE
Comment system

### ISSUE THREAD

**Issue by emperorjm** [sebastiaanluca/laravel-blog#1]
Is there an embedded commenting system? If not can you direct me to a useful solution. I am trying to integrate this solution into Laravel Spark.

**Comment by sebastiaanluca** [comment]
Not at this moment. It's really just a barebones, adjust-it-to-your-own-needs implementation of posts. The admin is there and fully functional, the front is where you do what you want.

I'm using Disqus on my blog (https://blog.sebastiaanluca.com) using a very simple Vue integration called [vue-disqus](https://www.npmjs.com/package/vue-disqus). Works great and simple, just have to provide the Disqus ID/shortname and that's it.

I'm also planning on writing some docs, but no ETA on that yet. If you have any questions, feel free to ask :)

**Comment by emperorjm** [comment]
Ok. Thanks.
